### ISSUE TITLE
References to Keycloak REST API docs

### ISSUE THREAD

**Issue by lsmith77** [p2-inc/phasetwo-docs#145]
There are a bunch of refences to https://www.keycloak.org/docs-api/17.0/rest-api/index.html within the docs, which is a 404.

I wonder if in general the links should rather be to https://www.keycloak.org/docs-api/latest/rest-api/index.html ?

**Comment by xgp** [comment]
Huzzah! When we wrote those sections, there was no `latest` alias. We can update them now. Thanks.
