### ISSUE TITLE
Nav on mobile renders incorrectly

### ISSUE THREAD

**Issue by xgp** [p2-inc/phasetwo-docs#32]
![00C9E6A1-1E57-453B-A27E-5A569AF3B1F4](https://user-images.githubusercontent.com/244253/164514198-e6848901-1b98-4e58-b8a7-d8c4569d3537.jpg)

When you click on the ||| menu, the menu renders in a way that cannot be used.

**Comment by xgp** [comment]
@jeffpatzer weird mobile bug on the docs I can't figure out. lmk if your css-fu is strong.

**Comment by xgp** [comment]
@pnzrr weird mobile bug on the docs I can't figure out. lmk if your css-fu is strong.

**Comment by jeffpatzer** [comment]
![Image](https://user-images.githubusercontent.com/178291/210021833-e804367a-347b-4ce2-af89-175085945582.png)

kung fu'd

**Comment by pnzrr** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/93841792/210021880-279fc6c9-8fc9-427e-a184-e3d94aba6dfe.png">

kung fu'd

**Comment by xgp** [comment]
Done in https://github.com/p2-inc/phasetwo-docs/commit/2983d26ca5103eddead781aa946c0420c9e3a961
