### ISSUE TITLE
[Article] Building self-serve on CockroachDB

### ISSUE THREAD

**Issue by xgp** [p2-inc/phasetwo-docs#49]
Draft a mutual blog post announcing Keycloak CRDB support and the launch of dedicated clusters built with Keycloak + CRDB serverless.

Similar based on an authorization product 
- https://www.cockroachlabs.com/blog/authzed-and-cockroachdb/
- https://www.cockroachlabs.com/blog/scale-out-oltp-database/

**Comment by xgp** [comment]
# Keycloak on CockroachDB: Scalable, resilient, open source, identity and access management

[Keycloak](https://www.keycloak.org/) has been a leader in the Identity and Access Management world since it's launch almost 8 years ago. The market for tools had several commercial offerings that failed to meet many business model and price needs, and Keycloak filled the hole with an open source offering. 

Fast-forward to today, Keycloak still leads with mature protocol implementations, hardened security, and a reliable architecture that has been battle-tested for years, under the stewardship of the maintainers at [Red Hat](https://www.redhat.com/). Whether deploying an in-house identity provider, or a user management system for a SaaS offering, Keycloak maintains a favorable position as an obvious choice.

With time, customer needs have evolved to include deploying in multiple regions, and operating across clouds. Because of operational complexity and architectural barriers, the Keycloak team decided to embark on a project to build a new underlying storage architecture. While promising, the project has taken longer than expected, and has yet to produce a production-ready result.

One of the great aspects of open source, is that it allows anyone to participate. Over a year ago, [Phase Two](https://phasetwo.io) decided to implement support for CockroachDB for the existing storage architecture in order to meet this growing customer demand. 

### What is Phase Two?

Phase Two helps SaaS builders accelerate time-to-market and enterprise adoption with powerful SSO, identity and user management features. To that end, Phase Two has created an enhanced distribution of Keycloak that bundles several essential [open source extensions](https://github.com/p2-inc) for modern SaaS use cases. Phase Two supports hosted and on-prem customers for a variety of use cases.


### How we built support for CockroachDB



 


### Let's get started
We get it! Here are a few links to help you jump-start your work:


#### Community
Because it's a drop-in replacement for Keycloak that doesn't require much configuration beyond the official guides, we haven't had much demand for additional documentation. That said, we're certainly open to building more content around it if you think it would drive demand. What would you suggest?

https://quay.io/repository/phasetwo/keycloak-crdb?tab=info

The database tier uses a managed CockroachDB service provided by [Cockroach Labs](https://www.cockroachlabs.com/). Phase Two is the only provider that is capable of hosting the current Keycloak distribution (the "legacy" store) using CockroachDB. Working with Cockroach Labs gives us the expertise and reliability from hosting thousands of customer clusters at massive scale.

**Comment by xgp** [comment]
@pnzrr Please review when you get a chance.

**Comment by pnzrr** [comment]
@xgp comment is edited, lgtm

**Comment by xgp** [comment]
1. meeting the customer where they are
2. support for managed (serverless, dedicated) and on-prem

**Comment by xgp** [comment]
Completed by https://github.com/p2-inc/phasetwo-docs/commit/d9c4331527845e74f5a077f8b44cd60a1034c10d
