### ISSUE TITLE
OpenAPI includes invalid response code

### ISSUE THREAD

**Issue by sweeneytr** [p2-inc/phasetwo-docs#91]
Not a big deal, but will produce a warning and affect code generation.

https://github.com/p2-inc/phasetwo-docs/blob/7fc50720729c5716bac7078a3cb6377b4d419f67/openapi.yaml#L1034

**Comment by xgp** [comment]
fixed in [c7a772b](https://github.com/p2-inc/phasetwo-docs/commit/c7a772b7d8358a27bd6e20abf083dd1f680bcc00)
